## Exercício 1: Vestibular

Considere que os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o percentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [2]:
# 1) Seu código aqui

pc_mat = df_mat / 24
pc_por = df_por / 18
pc_geo = df_geo /  8
pc_ing = df_ing /  8
pc_his = df_his /  8
pc_fis = df_fis /  12
pc_qui = df_qui /  12

In [3]:
# 2) Seu código aqui
total = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui
total

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [4]:
# 3) Seu código aqui
total/(24 + 18 + 8 + 8 + 8 + 12 + 12)

    Qt_acertos
0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
..         ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667

[100 rows x 1 columns]

In [11]:
# 4) Seu código aqui
total_gt_45 = total[total['Qt_acertos'] > 45]
total_aprovados = total_gt_45['Qt_acertos'].count()
print(f'Tota de alunos com nota maior que 45: {total_aprovados}')

Tota de alunos com nota maior que 45: 31

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [12]:
# seu código aqui 
#1 - DF de alunos desqualificados
df_eliminados = total[(df_mat['Qt_acertos'] == 0) | 
                      (df_fis['Qt_acertos'] == 0) | 
                      (df_qui['Qt_acertos'] == 0)]

df_eliminados

    Qt_acertos
3           32
6           29
10          31
12          42
14          31
20          53
25          27
26          40
27          50
33          39
35          48
49          19
56          39
65          24
66          31
72          50
73          37
74          39
84          26
89          63
92          40
94          25
98          40

In [15]:
total_eliminados = df_eliminados['Qt_acertos'].count()
print(f"Total de alunos eliminados: {total_eliminados}")

Total de alunos eliminados: 23

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [16]:
arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-83257660-6b16-47c1-ae31-382e92261142.c000.csv'
df = pd.read_csv(arquivo, sep=';')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346163 entries, 0 to 346162
Data columns (total 32 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   document_id                               346163 non-null  object
 1   paciente_id                               346163 non-null  object
 2   paciente_idade                            346163 non-null  int64
 3   paciente_dataNascimento                   346163 non-null  object
 4   paciente_enumSexoBiologico                346163 non-null  object
 5   paciente_racaCor_codigo                   346163 non-null  int64
 6   paciente_racaCor_valor                    346163 non-null  object
 7   paciente_endereco_coIbgeMunicipio         344049 non-null  object
 8   paciente_endereco_coPais                  344053 non-null  object
 9   paciente_endereco_nmMunicipio             344052 non-null  object
 10  paciente_endereco_nmPais                  344053 non-null  object
 11  paciente_endereco_uf                      344049 non-null  object
 12  paciente_endereco_cep                     311405 non-null  object
 13  paciente_nacionalidade_enumNacionalidade  346031 non-null  object
 14  estabelecimento_valor                     346163 non-null  int64
 15  estabelecimento_razaoSocial               346163 non-null  object
 16  estalecimento_noFantasia                  346163 non-null  object
 17  estabelecimento_municipio_codigo          346163 non-null  int64
 18  estabelecimento_municipio_nome            346163 non-null  object
 19  estabelecimento_uf                        346163 non-null  object
 20  vacina_grupoAtendimento_codigo            346150 non-null  float64
 21  vacina_grupoAtendimento_nome              345184 non-null  object
 22  vacina_categoria_codigo                   325743 non-null  float64
 23  vacina_categoria_nome                     325743 non-null  object
 24  vacina_lote                               346163 non-null  object
 25  vacina_fabricante_nome                    346163 non-null  object
 26  vacina_fabricante_referencia              343987 non-null  object
 27  vacina_dataAplicacao                      346163 non-null  object
 28  vacina_descricao_dose                     346163 non-null  object
 29  vacina_codigo                             346163 non-null  int64
 30  vacina_nome                               346154 non-null  object
 31  sistema_origem                            345764 non-null  object
dtypes: float64(2), int64(5), object(25)
memory usage: 84.5+ MB

In [22]:
df.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,2b93144a-d66a-45ac-8c8f-bee6e20561db-i0b0,fe8d2f96a81debfd82c2be5b9a5b597c8c3a11243e5b86...,23,1999-01-02,F,5,INDIGENA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,21PVCD389W,ASTRAZENECA/FIOCRUZ,149,2022-07-28,Reforço,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
1,dabf676c-dc7b-43bc-8ac0-3c3677f0c004-i0b0,9b47dd91739ef7a8f28f4e8c707340918b94c9eace2af6...,3,2019-12-10,M,3,PARDA,120060.0,10.0,TARAUACA,...,2.0,Faixa Etária,GC9016,PFIZER - PEDIÁTRICA MENOR DE 5 ANOS,28290,2023-03-07,1ª Dose,102,COVID-19 PFIZER - COMIRNATY PEDIÁTRICA MENOR D...,Novo PNI
2,c5b89122-8166-4f7e-9ef3-1a98c8e65d52-i0b0,578eff022445b36a42ef61a011ec5517523a563c5321a7...,20,2001-03-21,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FF8848,PFIZER,Organization/00394544000851,2021-10-25,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
3,dadf733f-1da4-4da3-96e1-a06653828e22-i0b0,bbe4aae9d47af6ffb30bbf8880caa0f72a905b28fa6c1a...,11,2010-02-08,M,99,SEM INFORMACAO,120001.0,10.0,ACRELANDIA,...,NaN,NaN,FP1176,PFIZER,Organization/28290,2022-01-18,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
4,9301b5d6-70ac-48b0-835d-a631e181693a-i0b0,7a3d2e2120e7384a246e0a91c9b660d431dcc62ae20881...,8,2013-07-27,M,1,BRANCA,120034.0,10.0,MANOEL URBANO,...,NaN,NaN,B202106081,Pendente Identificação,Organization/29501,2022-04-04,2ª Dose,98,COVID-19 SINOVAC - CORONAVAC,Novo PNI

In [23]:
# 1) Sua solução aqui
total_vacinas = df.shape[0]
print(f'Total de vacina aplicadas: {total_vacinas}')

Total de vacina aplicadas: 346163

In [25]:
# 2) 
total_pacientes_vacinados = df['paciente_id'].nunique()
print(f'Total de pacientes vacinados: {total_pacientes_vacinados}')

Total de pacientes vacinados: 290353

In [30]:
# 3) 
primeira_dose = df['vacina_descricao_dose'].unique()[1]
total_pacientes_primeira_dose = df['paciente_id'].loc[df['vacina_descricao_dose'] == primeira_dose].nunique()
print(f'Total de pacientes únicos que tomaram a 1ª Dose: {total_pacientes_primeira_dose}')

Total de pacientes únicos que tomaram a 1ª Dose: 139146

In [37]:
# 4) 
df_menor = df['paciente_id'].loc[df['paciente_idade'] < 18].unique()
total_menor_idade = df_menor.size
print(f'Total de pacientes vacinados menores de idade: {total_menor_idade}')

Total de pacientes vacinados menores de idade: 54672

In [42]:
# 5)
total_estabelecimentos_aplicou_vacina = df['estabelecimento_razaoSocial'].nunique()
print(f'Total de estabelecimentos que aplicaram vacina: {total_estabelecimentos_aplicou_vacina}')

Total de estabelecimentos que aplicaram vacina: 51

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vacinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [43]:
# 1) 
df_menor = df[df["paciente_idade"] < 18].copy()

In [44]:
# 2) 
df_menor.columns

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [45]:
# 3)
df_menor['vacina_categoria_nome'].value_counts()

Faixa Etária                                      34045
Outros                                             3701
Povos Indígenas                                    1848
Povos e Comunidades Tradicionais                    567
Trabalhadores de Saúde                              238
População Privada de Liberdade                       50
Comorbidades                                         33
Gestantes                                            23
Pessoas Institucionalizadas                           3
Pessoas com Deficiência                               3
Pessoas de 60 anos ou mais institucionalizadas        1
Trabalhadores da Educação                             1
Name: vacina_categoria_nome, dtype: int64

In [46]:
# 4)
lista_variaveis = ['estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf']
df_menor_lista = df_menor.loc[:,lista_variaveis]
df_menor_lista

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1,3810771,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE DE S DA FAMILIA DR JOSE LEONCIO GOMES ...,120060,TARAUACA,AC
3,3006166,PREFEITURA MUNICIPAL DE ACRELANDIA,UNIDADE DE SAUDE DA FAMILIA NORTON VITORINO BOHEN,120001,ACRELANDIA,AC
4,2000954,PREFEITURA MUNICIPAL DE MANUEL URBANO,UNIDADE DE SAUDE INACIO RIBEIRO DA SILVA,120034,MANOEL URBANO,AC
5,7436440,PREFEITURA MUNICIPAL DE ASSIS BRASIL,UNIDADE BASICA DE SAUDE GILDO FERREIRA DA SILVA,120005,ASSIS BRASIL,AC
7,2002914,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE SAUDE DA FAMILIA 25 DE AGOSTO,120020,CRUZEIRO DO SUL,AC
...,...,...,...,...,...,...
346147,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
346149,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
346151,2000067,PREFEITURA MUNICIPAL DE FEIJO,U S F FRANCISCA LIMA,120030,FEIJO,AC
346155,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
346158,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC

In [47]:
# 5)
df_menor_lista = df_menor_lista.drop_duplicates()
df_menor_lista.shape

(116, 6)